webDevlopment/digiLib/controller/librarians/routes.py
from flask import Blueprint,render_template, url_for, flash, redirect, request
from digiLib import webapp, db, bcrypt
from flask_login import login_user, current_user, logout_user, login_required
from digiLib.models import Users,Books
from digiLib.controller.librarians.forms import (RegistrationFormLib,LoginForm,UpdateAccountForm,
                                AddBooks,UpdateImageBook,RequestResetForm,ResetPasswordForm)
from digiLib.controller.librarians.utils import save_picture,save_picture_book

librarians = Blueprint('librarians',__name__)

@librarians.route("/Librarian/loginLib/home")
def homeLib():
    return render_template('home(Librarian).html')    

@librarians.route("/logout")
def logout():
    logout_user()
    flash('Logout Sucessfully', 'warning')
    return redirect(url_for('users.home'))

# Route for Registering Librarians
@librarians.route("/Librarian/registerLib", methods=['GET', 'POST'])
def registerLib():
    if current_user.is_authenticated:
        return redirect(url_for('librarians.homeLib'))
    form = RegistrationFormLib()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        typeofAcc = 'Librarian'
        user = Users(first_name=form.first_name.data,last_name=form.last_name.data,
            date_of_birth=form.date_of_birth.data,door_no=form.door_no.data,
            street_name=form.street_name.data,area_name=form.area_name.data,
            country=form.country.data,state=form.state.data,
            postal_code=form.postal_code.data,mobile_number=form.mobile_number.data,
            username=form.username.data,email=form.email.data, password=hashed_password,
            security = form.security.data,Account_type=typeofAcc)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('librarians.loginLib'))
    return render_template('registerLib.html', title='Register', form=form)






#Route for Librarians Login
@librarians.route("/Librarian/loginLib", methods=['GET', 'POST'])
def loginLib():
    if current_user.is_authenticated:
        return redirect(url_for('librarians.homeLib'))
    form = LoginForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(email=form.email.data,Account_type='Librarian').first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('librarians.homeLib')),flash('Login Successful!', 'success')
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('loginLib.html', title='Login', form=form)


#   Route for Registering New Books
@librarians.route("/Librarian/homeLib/addBooks",methods=['GET','POST'])
@login_required
def addBook():
    form = AddBooks()
    if form.validate_on_submit():
        book = Books(book_name=form.book_name.data,author_name=form.author_name.data,
            book_dept=form.book_dept.data,book_cost=form.book_cost.data,
            book_des=form.book_des.data,book_pub=form.book_pub.data,year_published=form.year_published.data,
            isbn_number=form.isbn_number.data,no_of_pages=form.no_of_pages.data,no_of_copies=form.no_of_copies.data,
            no_ofCopies=form.no_of_copies.data,floor_no=form.floor_no.data,rack_no=form.rack_no.data,shelf_no=form.shelf_no.data)
        db.session.add(book);db.session.commit()
        flash(f'{form.book_name.data} Added into Database successfully!','success')
        return redirect(url_for('librarians.Updatebookinfo',book=form.book_name.data))
    return render_template('addBook.html',title='Register Books',form=form)


@librarians.route("/Librarian/accountLib", methods=['GET', 'POST'])
@login_required
def accountLib():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('librarians.accountLib'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account(Librarians).html', title='Account',
                           image_file=image_file, form=form)



#Routes to Add Image to datebase
@librarians.route('/Librarian/homeLib/addBooks/addImage=<book>',methods=['GET','POST'])
def Updatebookinfo(book):
    form = UpdateImageBook()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture_book(form.picture.data)
            print(picture_file,book)
            updat = Books.query.filter_by(book_name=book).first()
            updat.image_file = str(picture_file)
            db.session.commit()
        flash(f'Image Added into Database successfully!','success')
        return redirect(url_for('librarians.homeLib'))
    return render_template('updateimage.html',form=form)


#Routes to Monitor Books for Librarians
@librarians.route('/Librarian/homeLib/MonitorBooks')
@login_required
def MonitorBooks():
    posts = BorrowBook.query.all()
    return render_template('MonitorBooks.html',posts=posts)

#Routes to Borrowed Books for Librarians
@librarians.route('/Librarian/homeLib/BorrowedBooks')
@login_required
def BorrowedBooks():
    return render_template('BorrowedBooks.html')

#Routes to Add Books for Librarians
@librarians.route('/Librarian/homeLib/MonitorStudents')
@login_required
def MonitorStudents():
    return render_template('MonitorStudents.html')

webDevlopment/digiLib/controller/users/routes.py
from flask import Blueprint,render_template, url_for, flash, redirect, request
from datetime import datetime, timedelta
from digiLib import webapp, db, bcrypt
from flask_login import login_user, current_user, logout_user, login_required
from digiLib.models import Users,Books,BorrowBook,Cart
from digiLib.controller.users.forms import RegistrationForm
from digiLib.controller.librarians.forms import LoginForm,UpdateAccountForm,RequestResetForm,ResetPasswordForm
from digiLib.controller.librarians.utils import save_picture
from digiLib.controller.users.utils import func_to_borrow

users = Blueprint('users',__name__)

@users.route("/")
@users.route("/home")
def home():
    return render_template('home.html')

@users.route("/logout")
def logout():
    logout_user()
    flash('Logout Sucessfully', 'warning')
    return redirect(url_for('users.home'))

#   Showing Books for User
@users.route('/User/home/showbooks')
def showBooks():
    page = request.args.get('page',1,type=int)
    posts = Books.query.paginate(page=page,per_page=4)
    return render_template('showbooks.html',posts=posts,title='Book-List')

@users.route("/User/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('users.login'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        typeofAcc = 'User'
        user = Users(first_name=form.first_name.data,last_name=form.last_name.data,
            date_of_birth=form.date_of_birth.data,door_no=form.door_no.data,
            street_name=form.street_name.data,area_name=form.area_name.data,
            country=form.country.data,state=form.state.data,
            postal_code=form.postal_code.data,mobile_number=form.mobile_number.data,
            typeofmembership=form.typeofmembership.data,
            username=form.username.data, email=form.email.data, password=hashed_password,
            security = form.security.data,Account_type=typeofAcc)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

@users.route("/User/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('users.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(email=form.email.data,Account_type='User').first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('users.home')),flash('Login Successful!', 'success')
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)

@users.route("/User/account", methods=['GET', 'POST'])
@login_required
def account():
    renewList,returnList = [],[]
    form = UpdateAccountForm()
    posts = BorrowBook.query.filter_by(username=current_user.username).all()
    if len(posts) == 0:flag = 1
    else:flag =0
    if request.method == 'POST':
        if request.form['submit'] == 'Add To Return List':
            print('Add to return List',len(posts));
            flash('Book Added to Return List', 'success')
            return redirect(url_for('users.account'))
        elif request.form['submit'] == 'Add To Renew List':
            print('Book Added to Renew List')
            flash('Book Added to Renew List', 'success')
            return redirect(url_for('users.home'))
        elif request.form['submit'] == 'Return All':
            print('Returning all Books',posts);
            flash('All Books Returned Sucessfully!', 'success')
            for i in range(len(posts)):
                post_book = Books.query.filter_by(book_name=posts[i].book_name,author_name=posts[i].author_name).first()
                post_book.no_of_copies+=1
                db.session.commit()
                db.session.delete(posts[i])
                db.session.commit()            
            return redirect(url_for('users.home'))
        elif request.form['submit'] == 'Renew All':
            print('Returning all Books')
            for i in range(len(posts)):
                post_book = Books.query.filter_by(book_name=posts[i].book_name,author_name=posts[i].author_name).first()
                post_book.no_of_copies+=1
                db.session.commit()
                posts[i].renew_time =datetime.now()+timedelta(minutes = 5)
                db.session.commit()
                print(posts[i].renew_time)
            flash('All Books Renewed Sucessfully!', 'success')
            return redirect(url_for('users.account'))

        if form.validate_on_submit():
            if form.picture.data:
                print(form.picture.data)
                picture_file = save_picture(form.picture.data)
                current_user.image_file = picture_file
            current_user.username = form.username.data
            current_user.email = form.email.data
            db.session.commit()
            flash('Your account has been updated!', 'success')
            return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form,posts=posts,flag=flag)


#Route Display Book for Users
@users.route('/User/home/showBooks/<int:book_id>/<flag>',methods=['GET','POST'])
def bookSingle(book_id,flag):
    post = Books.query.get_or_404(book_id);print(flag)
    print(post.isbn_number)
    if request.method == 'POST':
        if request.form['submit'] == 'Borrow':
            func_to_borrow(post,current_user)
            flash('Borrowed Books Sucessfully', 'success')
        elif request.form['submit'] == 'Add to Cart':
            print('We nailed it!')
            add_to_cart = Cart(book_name=post.book_name,author_name=post.author_name,
                book_dept=post.book_dept,isbn_number=post.isbn_number,image_file=post.image_file,
                username=current_user.username,typeofmembership=current_user.typeofmembership,
                no_of_copies=post.no_of_copies,first_name=current_user.first_name)
            db.session.add(add_to_cart)
            db.session.commit()
            flash('Added to Cart', 'success')
    return render_template('book.html',title = post.book_name,post = post,flag=flag)

#   Route for Cart List for Users
@users.route('/User/home/<usernam>/cart',methods=['GET','POST'])
def cartList(usernam):
    posts = Cart.query.filter_by(username=usernam).all()
    if len(posts) == 0:flag = 1
    else:flag =0
    if request.method == 'POST':
        if request.form['submit'] == 'Borrow':
            print('Borrow');
            for i in range(len(posts)):
                func_to_borrow(posts[i],current_user)
                db.session.delete(posts[i]);
                db.session.commit()
            flash('Borrowed Books Sucessfully', 'success')
    return render_template('cart.html',title='Cart',posts=posts,flag=flag)



@users.route('/User/forgot_password',methods=['GET','POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('users.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(email=form.email.data).first()
        token = user.get_reset_token()
        flash('An e-mail has been sent with instructions to reset the password.','info')
        print(token,type(user.username))
        return redirect(url_for('users.reset_password',username=user.username))
    return render_template('reset_request.html',title='Reset Password',form = form)

@users.route('/User/forgot_password/<username>',methods=['GET','POST'])
def reset_password(username):
    if current_user.is_authenticated:
        return redirect(url_for('users.home'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = Users.query.filter_by(username = username).first()
        print(user.password)
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_password.html',title='Reset Password',form = form)

webDevlopment/digiLib/templates/about.html
{% extends "layout.html" %}

{% block content %}

    <h2>About Devloper</h2>
    <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ url_for('static',filename='profile_pics/'+'default.jpg')}}" >
            <div class="media-body">

              <div class="article-metadata">

                <h5>Naresh Kumar K</h5>

                <small class="text-muted"> @ Glosys</small>

              </div>

              <p>A Vision Web Devloper implementor of websites that charming to look and feels Natural to Use Upon</p>

              
            </div>
            <button type="button" class="btn btn-outline-info">nPLU$ CoDec$</button>
          </article>
          



{% endblock content %}


webDevlopment/digiLib/templates/layout(librarian).html
<!DOCTYPE html>

<html>

<head>

    <!-- Required meta tags -->

    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">



    <!-- Bootstrap CSS -->

    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">



    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main(Lib).css') }}">



    {% if title %}

        <title>diGi-Lib - {{ title }}</title>

    {% else %}

        <title>diGi-Lib</title>

    {% endif %}

</head>

<body>

    <header class="site-header">

      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">

        <div class="container">

          <a class="navbar-brand mr-4" href="{{url_for('users.home')}}">Glosys diGi-Lib</a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">

            <span class="navbar-toggler-icon"></span>

          </button>

          <div class="collapse navbar-collapse" id="navbarToggle">

            <div class="navbar-nav mr-auto">

              <a class="nav-item nav-link" href="{{ url_for('librarians.homeLib') }}">Home</a>

              <a class="nav-item nav-link" href="#">About</a>

              <a class="nav-item nav-link" href="{{ url_for('librarians.addBook') }}">Register Books</a>

              <a class="nav-item nav-link" href="{{ url_for('users.showBooks') }}">Monitor Books</a>
              <a class="nav-item nav-link" href="{{ url_for('librarians.MonitorBooks') }}">Monitor Books</a>

              <a class="nav-item nav-link" href="{{ url_for('librarians.MonitorBooks') }}">Monitor Students</a>

              

            </div>

            <!-- Navbar Right Side -->

            <div class="navbar-nav">

              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('librarians.accountLib') }}">{{ current_user.first_name }} {{current_user.last_name}}</a>

                <a class="nav-item nav-link" href="{{ url_for('librarians.logout') }}">Logout</a>

              {% else %}

                <a class="nav-item nav-link" href="{{ url_for('librarians.loginLib') }}">Login</a>


              {% endif %}

            </div>

          </div>

        </div>

      </nav>

    </header>

    <main role="main" class="container">

      <div class="row">

        <div class="col-md-8">

          {% with messages = get_flashed_messages(with_categories=true) %}

            {% if messages %}

              {% for category, message in messages %}

                <div class="alert alert-{{ category }}">

                  {{ message }}

                </div>

              {% endfor %}

            {% endif %}

          {% endwith %}

          {% block content %}{% endblock %}

        </div>
        {% if current_user.is_authenticated %}
        <div class="col-md-4">

          <div class="content-section">

            <h3>Notifications</h3>

            <p class='text-muted'>You can put any information here you'd like.

              <ul class="list-group">

                
                  <br>

                <a href="{{url_for('librarians.MonitorBooks')}}"><button class="btn btn-outline-info" ><li> Monitor Borrowed Book </li></button></a>
                  <br>
                <a href="{{url_for('librarians.MonitorBooks')}}"><button class="btn btn-outline-info" ><li> Monitor Users </li></button></a>
                  <br>

                <li class="list-group-item list-group-item-light">Calendars</li>

                <li class="list-group-item list-group-item-light">etc</li>

              </ul>

            </p>

          </div>

        </div>
        {% endif %}

      </div>

    </main>





    <!-- Optional JavaScript -->

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>

</html>

webDevlopment/digiLib/templates/layout.html
<!DOCTYPE html>

<html>

<head>

    <!-- Required meta tags -->

    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">



    <!-- Bootstrap CSS -->

    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">



    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">



    {% if title %}

        <title>diGi-Lib - {{ title }}</title>

    {% else %}

        <title>diGi-Lib</title>

    {% endif %}

</head>

<body>

    <header class="site-header">

      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">

        <div class="container">

          <a class="navbar-brand mr-4" href="/">Glosys diGi-Lib</a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">

            <span class="navbar-toggler-icon"></span>

          </button>

          <div class="collapse navbar-collapse" id="navbarToggle">

            <div class="navbar-nav mr-auto">

              <a class="nav-item nav-link" href="{{ url_for('users.home') }}">Home</a>

              
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('users.cartList',usernam = current_user.username) }}">Cart</a>
                {%if title == 'Book-List' %}
                {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.showBooks') }}">Show Books</a>
                {% endif %}
                <!-- concept
                   url_fordatra('showeBooks')
                -->
                <a class="nav-item nav-link" href="#">e-BooKs</a>
              {% else %}
              <a class="nav-item nav-link" href="{{ url_for('librarians.registerLib') }}">Register Librarians</a>
              {% endif %}
              <a class="nav-item nav-link" href="#">About</a>
            </div>

            <!-- Navbar Right Side -->

            <div class="navbar-nav">

              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">{{ current_user.first_name }} {{current_user.last_name}}</a>

                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>

              {% else %}

                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>

                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>

              {% endif %}

            </div>

          </div>

        </div>

      </nav>

    </header>

    <main role="main" class="container">

      <div class="row">

        <div class="col-md-8">

          {% with messages = get_flashed_messages(with_categories=true) %}

            {% if messages %}

              {% for category, message in messages %}

                <div class="alert alert-{{ category }}">

                  {{ message }}

                </div>

              {% endfor %}

            {% endif %}

          {% endwith %}

          {% block content %}{% endblock %}

        </div>

        <div class="col-md-4">

          <div class="content-section">

            
            <center><button type="button" class="btn btn-outline-info">Notifications</button></center><br>
            <center><a href="#"><button type="button" class="btn btn-outline-info">ML Apps</button></a></center>

            <p class='text-muted'>Check it out

              <ul class="list-group"><center>

                  

                <li class="list-group-item list-group-item-light">Announcements</li>

                <li class="list-group-item list-group-item-light">Events</li>
                </center>
              </ul>

            </p>

          </div>

        </div>

      </div>

    </main>





    <!-- Optional JavaScript -->

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>

</html>

webDevlopment/digiLib/templates/layout_for_display_user.html
<!DOCTYPE html>

<html>

<head>

    <!-- Required meta tags -->

    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">



    <!-- Bootstrap CSS -->

    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">


    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">



    {% if title %}

        <title>diGi-Lib - {{ title }}</title>

    {% else %}

        <title>diGi-Lib</title>

    {% endif %}

</head>

<body>

    <header class="site-header">

      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">

        <div class="container">

          <a class="navbar-brand mr-4" href="/">Glosys diGi-Lib</a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">

            <span class="navbar-toggler-icon"></span>

          </button>

          <div class="collapse navbar-collapse" id="navbarToggle">

            <div class="navbar-nav mr-auto">

              <a class="nav-item nav-link" href="{{ url_for('users.home') }}">Home</a>

              <a class="nav-item nav-link" href="#">About</a>
              {% if current_user.is_authenticated %}
                {%if title == 'Book-List' %}
                  <a class="nav-item nav-link" href="#">Not Books</a>
                {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.showBooks') }}">Show Books</a>
                <a class="nav-item nav-link" href="{{ url_for('users.cartList',usernam = current_user.username) }}">Cart</a>
                {% endif %}
              {% else %}
              <a class="nav-item nav-link" href="{{ url_for('librarians.registerLib') }}">Register Librarians</a>
              {% endif %}
            </div>

            <!-- Navbar Right Side -->

            <div class="navbar-nav">

              {% if current_user.is_authenticated %}

                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">{{ current_user.first_name }} {{current_user.last_name}}</a>

                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>

              {% else %}

                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>

                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>

              {% endif %}

            </div>

          </div>

        </div>

      </nav>

    </header>

    <main role="main" class="container">

      <div class="row">

        <div class="col-md-8">

          {% with messages = get_flashed_messages(with_categories=true) %}

            {% if messages %}

              {% for category, message in messages %}

                <div class="alert alert-{{ category }}">

                  {{ message }}

                </div>

              {% endfor %}

            {% endif %}

          {% endwith %}

          {% block content %}{% endblock %}

        </div>

        <div class="col-md-4">

          <div class="content-section">

            <h3>Book Image</h3>
            <img  src="{{ url_for('static',filename='book_pics/'+post.image_file)}}">
          </div>

        </div>

      </div>

    </main>





    <!-- Optional JavaScript -->

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>

</html>

webDevlopment/digiLib/templates/showbooks.html
{% if current_user.Account_type == 'Librarian' %}
  {% extends "layout(librarian).html" %}  
{% else %}
{% extends "layout.html" %}

{% block content %}

    <h1>Books</h1>
    {% for post in posts.items %}

        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ url_for('static',filename='book_pics/'+post.image_file)}}" >
            <div class="media-body">

              <div class="article-metadata">

                <h5><a class="mr-2" href="{{ url_for('users.bookSingle',book_id=post.id,flag='user') }}">{{ post.book_name }} &nbsp - {{post.book_dept}}</a></h5>

                <small class="text-muted"> by {{ post.author_name }}</small>

              </div>
              {% if current_user.Account_type == 'User' %}
              <p>{{ post.book_des }}</p>
              {% endif %}
              <div class="article-metadata">
              <h6 class="article-content">Copies Left : {{ post.no_of_copies }}</h6></div>
              
                <h5 class="article-content">Book Publisher: &nbsp{{ post.book_pub }}</h5>
            

          </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
        <a class="btn btn-info mb-4" href="{{ url_for('users.showBooks',page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('users.showBooks',page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...  
      {% endif %}
    {% endfor %} 
{% endblock content %}

{% endif %}
